apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: default
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
           "--context=git://github.com/Traktopel/wpov.git#refs/heads/wpov-live",
           "--destination=296062574090.dkr.ecr.eu-central-1.amazonaws.com/repo
           "--context-sub-path=tasky"]

  restartPolicy: Never
