- name: gather facts
  amazon.aws.ec2_metadata_facts:
    metadata_token_ttl_seconds: 240

- name: print
  debug:
    msg: "{{ ansible_ec2_instance_identity_document_accountid }}"

- name: Add repository
  ansible.builtin.yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Enable Repo
  ansible.builtin.command: percona-release enable psmdb-60 release

- name: Install mongo
  ansible.builtin.yum:
    name: percona-server-mongodb 
    state: present

- name: start mongod
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true

- name: load mongodb auth script
  ansible.builtin.template:
    src: create-user.js.j2
    dest: /tmp/create-user.js
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r

- name: add iam-role-user
  ansible.builtin.shell: mongosh < /tmp/create-user.js
  args:
    executable: /bin/bash

- name: gen-key-mongo
  ansible.builtin.shell: openssl rand -base64 756 > /etc/mongodb-keyfile
  args:
    executable: /bin/bash

- name: change permission
  ansible.builtin.file:
    path: /etc/mongodb-keyfile
    owner: mongod
    group: mongod 
    mode: '0400'

- name: reconfigure mongodb
  ansible.builtin.copy:
    src: files/mongod.conf
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: start mongod
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true

- name: Enable Repo
  ansible.builtin.command: percona-release enable pbm release


- name: Install pbm
  ansible.builtin.yum:
    name: percona-backup-mongodb
    state: present

- name: start rs
  ansible.builtin.shell: mongosh < rs.initiate()
  args:
    executable: /bin/bash

- name: pbm-config-url
  ansible.builtin.copy:
    src: files/pbm-agent
    dest: /etc/sysconfig/pbm-agent
    owner: root
    group: root
    mode: u=rw,g=r,o=


- name: pbm config storage file
  ansible.builtin.template:
    src: pbm-coonfig.yaml.j2
    dest: /tmp/pbm-config.yaml
    owner: root
    group: wheel
    mode: u=rw,g=r,o=r

- name: Enable pbm storage
  ansible.builtin.command: pbm config --file /tmp/pbm-config.yaml

- name: start pbm-agent
  ansible.builtin.service:
    name: pbm-agent
    state: restartd
    enabled: true

- name: Enable pbm storage
  ansible.builtin.command: pbm backup

