apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: tasky
  name: tasky
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tasky
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasky
    spec:
      containers:
      - image: 418272768514.dkr.ecr.eu-central-1.amazonaws.com/repo:latest
        imagePullPolicy: Always
        name: repo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: MONGODB_URI
          value: "mongodb://database-svc:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authMechanism=MONGODB-AWS&appName=mongosh+2.3.0"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
